# Generated by Django 4.1.7 on 2023-04-06 12:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('teststack', '0003_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Htmlfieldtry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', tinymce.models.HTMLField()),
            ],
        ),
    ]
