# Generated by Django 4.1.7 on 2023-04-11 11:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('teststack', '0004_htmlfieldtry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
