# Generated by Django 4.1.7 on 2023-04-17 16:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('teststack', '0008_bugcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugcomments',
            name='comment',
            field=tinymce.models.HTMLField(),
        ),
    ]
