# Generated by Django 4.1.7 on 2023-04-17 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teststack', '0009_alter_bugcomments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugcomments',
            old_name='post',
            new_name='bug',
        ),
        migrations.AlterField(
            model_name='bugcomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teststack.bugcomments'),
        ),
    ]
