# Generated by Django 4.1.7 on 2023-04-19 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teststack', '0010_rename_post_bugcomments_bug_alter_bugcomments_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseOutcome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iteration', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('Untested', 'Untested'), ('passed', 'Passed'), ('failed', 'Failed'), ('failed but ignorable', 'Failed but Ignorable'), ('comment awaited', 'Comment Awaited')], default='Untested', max_length=50)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Assignee', to=settings.AUTH_USER_MODEL)),
                ('bug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teststack.bug')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teststack.testcase')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
